version: "3.8"

services:
  classificador:
    build: ./classificador
    container_name: classificador
    ports:
      - "5001:5001"
    volumes:
      - shared_data:/shared
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
    restart: always

  gateway_api:
    build: ./gateway_api
    container_name: gateway_api
    ports:
      - "5000:5000"
    volumes:
      - shared_data:/shared
    depends_on:
      - classificador
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
    env_file:
      - .env
    restart: always

volumes:
  shared_data:
